import 'package:flutter/material.dart';
import 'package:ncc_cadet/models/notification_model.dart';
import 'package:ncc_cadet/providers/user_provider.dart';
import 'package:ncc_cadet/services/notification_service.dart';
import 'package:provider/provider.dart';
import 'package:ncc_cadet/utils/theme.dart';

class SendNotificationPage extends StatefulWidget {
  const SendNotificationPage({super.key});

  @override
  State<SendNotificationPage> createState() => _SendNotificationPageState();
}

class _SendNotificationPageState extends State<SendNotificationPage> {
  final _formKey = GlobalKey<FormState>();

  // Controllers for the notification content
  final TextEditingController _titleController = TextEditingController();
  final TextEditingController _bodyController = TextEditingController();

  // Toggle for high-priority alerts
  String _targetYear = 'All'; // Target Audience
  bool _isImportant = false;
  bool _isLoading = false;

  Future<void> _sendNotification() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final user = Provider.of<UserProvider>(context, listen: false).user;
      if (user == null) {
        throw Exception("User session error");
      }

      final notification = NotificationModel(
        id: '', // Generated by Firestore
        title: _titleController.text.trim(),
        message: _bodyController.text.trim(),
        type: 'organization',
        targetYear: _targetYear,
        targetId: user.organizationId,
        isRead: false,
        createdAt: DateTime.now(),
      );

      await NotificationService().sendNotification(notification);

      if (mounted) {
        _showSuccessDialog();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error: $e"), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        iconTheme: const IconThemeData(color: Colors.white),
        title: const Text(
          "Send Notification",
          style: TextStyle(color: Colors.white),
        ),
        backgroundColor: AppTheme.navyBlue,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(
            Icons.keyboard_arrow_left,
            color: Colors.white,
            size: 28,
          ),
          onPressed: () => Navigator.maybePop(context),
        ),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(1),
          child: Divider(color: Colors.grey.shade200, height: 1),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Guidance Text
              const Text(
                "Create an announcement for all cadets in your unit. "
                "Important alerts will be highlighted in their feed.",
                style: TextStyle(color: Colors.grey, fontSize: 14),
              ),
              const SizedBox(height: 30),

              // Notification Title
              _buildLabel("Notification Title"),
              TextFormField(
                controller: _titleController,
                validator: (value) =>
                    value!.isEmpty ? "Please enter a title" : null,
                style: const TextStyle(fontWeight: FontWeight.bold),
                decoration: _inputDecoration("e.g. Mandatory Parade Update"),
              ),
              const SizedBox(height: 24),

              // Notification Body
              _buildLabel("Message Content"),
              TextFormField(
                controller: _bodyController,
                validator: (value) =>
                    value!.isEmpty ? "Please enter message content" : null,
                maxLines: 6,
                decoration: _inputDecoration(
                  "Enter the details of your notification here...",
                ),
              ),
              const SizedBox(height: 24),

              // Target Audience
              _buildLabel("Target Audience"),
              DropdownButtonFormField<String>(
                initialValue: _targetYear,
                decoration: _inputDecoration("Select Year"),
                items: ['All', '1st Year', '2nd Year', '3rd Year']
                    .map(
                      (label) =>
                          DropdownMenuItem(value: label, child: Text(label)),
                    )
                    .toList(),
                onChanged: (val) => setState(() => _targetYear = val!),
              ),
              const SizedBox(height: 24),

              // Important Toggle Section
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: _isImportant
                      ? AppTheme.lightBlueBg
                      : Colors.grey.shade50,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(
                    color: _isImportant
                        ? AppTheme.accentBlue
                        : Colors.grey.shade200,
                  ),
                ),
                child: SwitchListTile(
                  contentPadding: EdgeInsets.zero,
                  title: const Text(
                    "Mark as Important",
                    style: TextStyle(fontWeight: FontWeight.bold),
                  ),
                  subtitle: const Text(
                    "Highlight this alert with a blue badge",
                  ),
                  secondary: Icon(
                    Icons.priority_high,
                    color: _isImportant ? AppTheme.navyBlue : Colors.grey,
                  ),
                  value: _isImportant,
                  activeThumbColor: AppTheme.navyBlue,
                  onChanged: (bool value) {
                    setState(() {
                      _isImportant = value;
                    });
                  },
                ),
              ),

              const SizedBox(height: 40),

              // Submit Button
              SizedBox(
                width: double.infinity,
                height: 55,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _sendNotification,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppTheme.navyBlue,
                    disabledBackgroundColor: Colors.grey.shade300,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                    elevation: 0,
                  ),
                  child: _isLoading
                      ? const CircularProgressIndicator(color: Colors.white)
                      : const Text(
                          "Broadcast Notification",
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  // --- UI Helpers ---

  Widget _buildLabel(String label) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Text(
        label,
        style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
      ),
    );
  }

  InputDecoration _inputDecoration(String hint) {
    return InputDecoration(
      hintText: hint,
      hintStyle: TextStyle(color: Colors.grey.shade400, fontSize: 14),
      filled: true,
      fillColor: Colors.white,
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: BorderSide(color: Colors.grey.shade200),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: const BorderSide(color: AppTheme.accentBlue, width: 1.5),
      ),
    );
  }

  void _showSuccessDialog() {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        title: const Text("Sent Successfully"),
        content: const Text(
          "Your notification has been broadcast to all cadets.",
        ),
        actions: [
          TextButton(
            onPressed: () {
              Navigator.pop(context); // Close dialog
              Navigator.pop(context); // Go back to dashboard
            },
            child: const Text(
              "OK",
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
    );
  }
}
