// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpQKAt_j3fQnN1o_yhFzaTGV7hsmWea1w',
    appId: '1:435777837540:web:e79edf0666b64e2acfcff1',
    messagingSenderId: '435777837540',
    projectId: 'cadet-hub-7ac2d',
    authDomain: 'cadet-hub-7ac2d.firebaseapp.com',
    storageBucket: 'cadet-hub-7ac2d.firebasestorage.app',
    measurementId: 'G-EWYXKK9JD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1hDBzIPKWpk0K9BtiJf2rQXl4pvGFle4',
    appId: '1:435777837540:android:56f730c59c2efa31cfcff1',
    messagingSenderId: '435777837540',
    projectId: 'cadet-hub-7ac2d',
    storageBucket: 'cadet-hub-7ac2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLtoMJ4PtHtwS1C8KPC0XguWORl76EC-k',
    appId: '1:435777837540:ios:c3c1ad634d78a66ecfcff1',
    messagingSenderId: '435777837540',
    projectId: 'cadet-hub-7ac2d',
    storageBucket: 'cadet-hub-7ac2d.firebasestorage.app',
    iosBundleId: 'com.example.nccCadet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLtoMJ4PtHtwS1C8KPC0XguWORl76EC-k',
    appId: '1:435777837540:ios:c3c1ad634d78a66ecfcff1',
    messagingSenderId: '435777837540',
    projectId: 'cadet-hub-7ac2d',
    storageBucket: 'cadet-hub-7ac2d.firebasestorage.app',
    iosBundleId: 'com.example.nccCadet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpQKAt_j3fQnN1o_yhFzaTGV7hsmWea1w',
    appId: '1:435777837540:web:31acc99cd8673268cfcff1',
    messagingSenderId: '435777837540',
    projectId: 'cadet-hub-7ac2d',
    authDomain: 'cadet-hub-7ac2d.firebaseapp.com',
    storageBucket: 'cadet-hub-7ac2d.firebasestorage.app',
    measurementId: 'G-HH4H3B8CRY',
  );
}
