import 'package:flutter/material.dart';
import 'package:ncc_cadet/models/leave_model.dart';
import 'package:ncc_cadet/models/notification_model.dart';
import 'package:ncc_cadet/providers/user_provider.dart';
import 'package:ncc_cadet/services/leave_service.dart';
import 'package:ncc_cadet/services/notification_service.dart';
import 'package:ncc_cadet/utils/theme.dart'; // Import AppTheme
import 'package:provider/provider.dart';

class CadetLeaveRequestScreen extends StatefulWidget {
  const CadetLeaveRequestScreen({super.key});

  @override
  State<CadetLeaveRequestScreen> createState() =>
      _CadetLeaveRequestScreenState();
}

class _CadetLeaveRequestScreenState extends State<CadetLeaveRequestScreen> {
  // Controllers
  final TextEditingController _fromDateController = TextEditingController();
  final TextEditingController _toDateController = TextEditingController();
  final TextEditingController _reasonController = TextEditingController();
  bool _isLoading = false;

  @override
  void dispose() {
    _fromDateController.dispose();
    _toDateController.dispose();
    _reasonController.dispose();
    super.dispose();
  }

  Future<void> _selectDate(TextEditingController controller) async {
    final picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: const ColorScheme.light(
              primary: AppTheme.navyBlue, // Header background color
              onPrimary: Colors.white, // Header text color
              onSurface: AppTheme.navyBlue, // Body text color
            ),
            textButtonTheme: TextButtonThemeData(
              style: TextButton.styleFrom(
                foregroundColor: AppTheme.navyBlue, // Button text color
              ),
            ),
          ),
          child: child!,
        );
      },
    );
    if (picked != null) {
      setState(() {
        controller.text =
            "${picked.year}-${picked.month.toString().padLeft(2, '0')}-${picked.day.toString().padLeft(2, '0')}";
      });
    }
  }

  Future<void> _submitLeaveRequest() async {
    if (_fromDateController.text.isEmpty ||
        _toDateController.text.isEmpty ||
        _reasonController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text("Please fill all fields"),
          backgroundColor: AppTheme.error,
        ),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final userProvider = Provider.of<UserProvider>(context, listen: false);
      final user = userProvider.user;

      if (user == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text("User session error"),
            backgroundColor: AppTheme.error,
          ),
        );
        return;
      }

      final leave = LeaveModel(
        id: '', // Auto-generated by Firestore
        cadetId: user.uid,
        cadetName: user.name,
        reason: _reasonController.text.trim(),
        startDate: _fromDateController.text,
        endDate: _toDateController.text,
        status: 'Pending',
        organizationId: user.organizationId,
        cadetYear: user.year, // Use the user's year
        createdAt: DateTime.now(),
      );

      await LeaveService().requestLeave(leave);

      // Notify Organization (Officer)
      await NotificationService().sendNotification(
        NotificationModel(
          id: '',
          title: 'New Leave Request',
          message: '${user.name} has requested leave.',
          type: 'organization',
          targetId: user.organizationId,
          createdAt: DateTime.now(),
        ),
      );

      if (mounted) {
        showDialog(
          context: context,
          builder: (_) => AlertDialog(
            title: const Text(
              "Request Submitted",
              style: TextStyle(color: AppTheme.navyBlue),
            ),
            content: const Text(
              "Your leave request has been submitted for approval.",
            ),
            actions: [
              TextButton(
                onPressed: () {
                  Navigator.pop(context); // Close Dialog
                  Navigator.pop(context); // Close Screen
                },
                child: const Text(
                  "OK",
                  style: TextStyle(
                    color: AppTheme.navyBlue,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error: $e"), backgroundColor: AppTheme.error),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white, // Or AppTheme.lightGrey for off-white
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        centerTitle: true,
        leading: IconButton(
          icon: const Icon(Icons.keyboard_arrow_left, color: AppTheme.navyBlue),
          onPressed: () => Navigator.maybePop(context),
        ),
        title: const Text(
          "Leave Request",
          style: TextStyle(
            color: AppTheme.navyBlue,
            fontWeight: FontWeight.bold,
            fontSize: 18,
          ),
        ),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(1),
          child: Divider(color: Colors.grey.shade200, height: 1),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Info Card
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: AppTheme.lightBlueBg,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: AppTheme.accentBlue.withOpacity(0.3)),
              ),
              child: Row(
                children: [
                  const Icon(Icons.info_outline, color: AppTheme.accentBlue),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      "Requests must be submitted at least 3 days in advance.",
                      style: TextStyle(
                        color: AppTheme.navyBlue.withOpacity(0.8),
                        fontSize: 13,
                      ),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 30),

            // Date Selection Row
            Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      _buildLabel("From Date"),
                      GestureDetector(
                        onTap: () => _selectDate(_fromDateController),
                        child: AbsorbPointer(
                          child: _buildTextField(
                            _fromDateController,
                            hint: "Select Date",
                            icon: Icons.calendar_today_outlined,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      _buildLabel("To Date"),
                      GestureDetector(
                        onTap: () => _selectDate(_toDateController),
                        child: AbsorbPointer(
                          child: _buildTextField(
                            _toDateController,
                            hint: "Select Date",
                            icon: Icons.event_outlined,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 24),

            // Reason Field
            _buildLabel("Reason for Leave"),
            _buildTextField(
              _reasonController,
              hint: "Please explain why you need leave...",
              maxLines: 5,
            ),
            const SizedBox(height: 40),

            // Submit Button
            SizedBox(
              height: 56,
              child: ElevatedButton(
                onPressed: _isLoading ? null : _submitLeaveRequest,
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppTheme.navyBlue,
                  elevation: 2,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
                child: _isLoading
                    ? const SizedBox(
                        height: 24,
                        width: 24,
                        child: CircularProgressIndicator(
                          color: Colors.white,
                          strokeWidth: 2,
                        ),
                      )
                    : const Text(
                        "Submit Request",
                        style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                      ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildLabel(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0, left: 4),
      child: Text(
        text,
        style: const TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w600,
          color: AppTheme.navyBlue,
        ),
      ),
    );
  }

  Widget _buildTextField(
    TextEditingController controller, {
    String? hint,
    int maxLines = 1,
    IconData? icon,
  }) {
    return TextFormField(
      controller: controller,
      maxLines: maxLines,
      style: const TextStyle(color: Colors.black87),
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: TextStyle(color: Colors.grey.shade400, fontSize: 14),
        prefixIcon: icon != null
            ? Icon(icon, color: AppTheme.navyBlue.withOpacity(0.6), size: 20)
            : null,
        filled: true,
        fillColor: Colors.grey.shade50,
        contentPadding: const EdgeInsets.all(16),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: Colors.grey.shade300),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: Colors.grey.shade300),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: AppTheme.navyBlue, width: 1.5),
        ),
      ),
    );
  }
}
