import 'package:flutter/material.dart';
import 'package:ncc_cadet/models/leave_model.dart';
import 'package:ncc_cadet/providers/user_provider.dart';
import 'package:ncc_cadet/services/leave_service.dart';
import 'package:provider/provider.dart';

class CadetLeaveRequestScreen extends StatefulWidget {
  const CadetLeaveRequestScreen({super.key});

  @override
  State<CadetLeaveRequestScreen> createState() =>
      _CadetLeaveRequestScreenState();
}

class _CadetLeaveRequestScreenState extends State<CadetLeaveRequestScreen> {
  // Controllers to manage input text
  final TextEditingController _paradeController = TextEditingController(
    text: "Annual Training Camp Parade",
  );
  final TextEditingController _fromDateController = TextEditingController();
  final TextEditingController _toDateController = TextEditingController();
  final TextEditingController _reasonController = TextEditingController();

  @override
  void dispose() {
    _paradeController.dispose();
    _fromDateController.dispose();
    _toDateController.dispose();
    _reasonController.dispose();
    super.dispose();
  }

  Future<void> _selectDate(TextEditingController controller) async {
    final picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );
    if (picked != null) {
      setState(() {
        controller.text =
            "${picked.year}-${picked.month.toString().padLeft(2, '0')}-${picked.day.toString().padLeft(2, '0')}";
      });
    }
  }

  Future<void> _submitLeaveRequest() async {
    if (_fromDateController.text.isEmpty ||
        _toDateController.text.isEmpty ||
        _reasonController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text("Please fill all fields"),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    try {
      final userProvider = Provider.of<UserProvider>(context, listen: false);
      final user = userProvider.user;

      if (user == null) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(const SnackBar(content: Text("User session error")));
        return;
      }

      final leave = LeaveModel(
        id: '', // Auto-generated by Firestore
        cadetId: user.uid,
        cadetName: user.name,
        reason: _reasonController.text.trim(),
        startDate: _fromDateController.text,
        endDate: _toDateController.text,
        status: 'Pending',
        organizationId: user.organizationId,
        createdAt: DateTime.now(),
      );

      await LeaveService().requestLeave(leave);

      if (mounted) {
        showDialog(
          context: context,
          builder: (_) => AlertDialog(
            title: const Text("Request Submitted"),
            content: const Text(
              "Your leave request has been submitted for approval.",
            ),
            actions: [
              TextButton(
                onPressed: () {
                  Navigator.pop(context); // Close Dialog
                  Navigator.pop(context); // Close Screen
                },
                child: const Text("OK"),
              ),
            ],
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error: $e"), backgroundColor: Colors.red),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        centerTitle: true,
        leading: IconButton(
          icon: const Icon(Icons.chevron_left, color: Colors.black87, size: 30),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          "Leave Request",
          style: TextStyle(
            color: Colors.black87,
            fontWeight: FontWeight.bold,
            fontSize: 18,
          ),
        ),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(1),
          child: Divider(color: Colors.grey.shade200, height: 1),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Removed Parade Name field as per typical leave requests not tied to single parade usually, or keep it optional?
            // The mockup had it. I'll keep it but maybe it should be "Type of Leave" or just remove it if not in data model.
            // My LeaveModel doesn't have paradeName. I'll remove it or repurpose it.
            // Let's remove it for now to match the model.
            _buildLabel("From Date"),
            GestureDetector(
              onTap: () => _selectDate(_fromDateController),
              child: AbsorbPointer(
                child: _buildTextField(
                  _fromDateController,
                  hint: "YYYY-MM-DD",
                  icon: Icons.calendar_today,
                ),
              ),
            ),
            const SizedBox(height: 20),

            _buildLabel("To Date"),
            GestureDetector(
              onTap: () => _selectDate(_toDateController),
              child: AbsorbPointer(
                child: _buildTextField(
                  _toDateController,
                  hint: "YYYY-MM-DD",
                  icon: Icons.calendar_today,
                ),
              ),
            ),
            const SizedBox(height: 20),

            _buildLabel("Reason for Leave"),
            _buildTextField(
              _reasonController,
              hint:
                  "Please provide a detailed reason for your leave request...",
              maxLines: 5,
            ),
            const SizedBox(height: 20),

            const Text(
              "*All leave requests must be submitted at least 3 days in advance.",
              style: TextStyle(
                color: Colors.red,
                fontSize: 13,
                fontWeight: FontWeight.w500,
              ),
            ),
            const SizedBox(height: 30),

            SizedBox(
              width: double.infinity,
              height: 50,
              child: ElevatedButton(
                onPressed: _submitLeaveRequest,
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF1D5CFF),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(4),
                  ),
                  elevation: 0,
                ),
                child: const Text(
                  "Submit Request",
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  // Helper widget for input labels
  Widget _buildLabel(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Text(
        text,
        style: const TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w500,
          color: Colors.black87,
        ),
      ),
    );
  }

  // Helper widget for consistent text fields
  Widget _buildTextField(
    TextEditingController controller, {
    String? hint,
    bool readOnly = false,
    bool filled = false,
    int maxLines = 1,
    IconData? icon,
  }) {
    return TextField(
      controller: controller,
      readOnly: readOnly,
      maxLines: maxLines,
      decoration: InputDecoration(
        hintText: hint,
        suffixIcon: icon != null
            ? Icon(icon, color: Colors.grey, size: 20)
            : null,
        hintStyle: TextStyle(color: Colors.grey.shade400, fontSize: 14),
        filled: filled,
        fillColor: filled ? Colors.grey.shade100 : Colors.white,
        contentPadding: const EdgeInsets.symmetric(
          horizontal: 12,
          vertical: 12,
        ),
        enabledBorder: OutlineInputBorder(
          borderSide: BorderSide(color: Colors.grey.shade200),
          borderRadius: BorderRadius.circular(4),
        ),
        focusedBorder: OutlineInputBorder(
          borderSide: const BorderSide(color: Color(0xFF1D5CFF)),
          borderRadius: BorderRadius.circular(4),
        ),
      ),
    );
  }
}
